/** Constants */
const PREFIX = '@@AWX';
/** UI */
export const UI = `${PREFIX}/UI`;
export const ERROR = `${PREFIX}/ERROR`;
export const LOADING = `${PREFIX}/LOADING`;
export const NOOP = `${PREFIX}/NOOP`;
export const MULTI = `${PREFIX}/MULTI`;
export const GO = `${PREFIX}/GO`;
export const ENTITY = `${PREFIX}/ENTITY`;
/** Jobs */
export const JOBS_RUN_REQUEST = `${PREFIX}/JOBS_RUN_REQUEST`;
export const JOBS_RUN_SUCCESS = `${PREFIX}/JOBS_RUN_SUCCESS`;
export const JOBS_RUN_FAILURE = `${PREFIX}/JOBS_RUN_FAILURE`;
/** Labs */
export const LABS_INDEX_REQUEST = `${PREFIX}/LABS_INDEX_REQUEST`;
export const LABS_INDEX_SUCCESS = `${PREFIX}/LABS_INDEX_SUCCESS`;
export const LABS_INDEX_FAILURE = `${PREFIX}/LABS_INDEX_FAILURE`;
export const LABS_CREATE_REQUEST = `${PREFIX}/LABS_CREATE_REQUEST`;
export const LABS_CREATE_SUCCESS = `${PREFIX}/LABS_CREATE_SUCCESS`;
export const LABS_CREATE_FAILURE = `${PREFIX}/LABS_CREATE_FAILURE`;
export const LABS_DELETE_REQUEST = `${PREFIX}/LABS_DELETE_REQUEST`;
export const LABS_DELETE_SUCCESS = `${PREFIX}/LABS_DELETE_SUCCESS`;
export const LABS_DELETE_FAILURE = `${PREFIX}/LABS_DELETE_FAILURE`;
export const LABS_UPDATE_REQUEST = `${PREFIX}/LABS_UPDATE_REQUEST`;
export const LABS_UPDATE_SUCCESS = `${PREFIX}/LABS_UPDATE_SUCCESS`;
export const LABS_UPDATE_FAILURE = `${PREFIX}/LABS_UPDATE_FAILURE`;
export const LABS_SHOW_REQUEST = `${PREFIX}/LABS_SHOW_REQUEST`;
export const LABS_SHOW_SUCCESS = `${PREFIX}/LABS_SHOW_SUCCESS`;
export const LABS_SHOW_FAILURE = `${PREFIX}/LABS_SHOW_FAILURE`;
/** Participants */
export const PARTICIPANTS_INDEX_REQUEST = `${PREFIX}/PARTICIPANTS_INDEX_REQUEST`;
export const PARTICIPANTS_INDEX_SUCCESS = `${PREFIX}/PARTICIPANTS_INDEX_SUCCESS`;
export const PARTICIPANTS_INDEX_FAILURE = `${PREFIX}/PARTICIPANTS_INDEX_FAILURE`;
export const PARTICIPANTS_CREATE_REQUEST = `${PREFIX}/PARTICIPANTS_CREATE_REQUEST`;
export const PARTICIPANTS_CREATE_SUCCESS = `${PREFIX}/PARTICIPANTS_CREATE_SUCCESS`;
export const PARTICIPANTS_CREATE_FAILURE = `${PREFIX}/PARTICIPANTS_CREATE_FAILURE`;
export const PARTICIPANTS_DELETE_REQUEST = `${PREFIX}/PARTICIPANTS_DELETE_REQUEST`;
export const PARTICIPANTS_DELETE_SUCCESS = `${PREFIX}/PARTICIPANTS_DELETE_SUCCESS`;
export const PARTICIPANTS_DELETE_FAILURE = `${PREFIX}/PARTICIPANTS_DELETE_FAILURE`;
export const PARTICIPANTS_UPDATE_REQUEST = `${PREFIX}/PARTICIPANTS_UPDATE_REQUEST`;
export const PARTICIPANTS_UPDATE_SUCCESS = `${PREFIX}/PARTICIPANTS_UPDATE_SUCCESS`;
export const PARTICIPANTS_UPDATE_FAILURE = `${PREFIX}/PARTICIPANTS_UPDATE_FAILURE`;
export const PARTICIPANTS_SHOW_REQUEST = `${PREFIX}/PARTICIPANTS_SHOW_REQUEST`;
export const PARTICIPANTS_SHOW_SUCCESS = `${PREFIX}/PARTICIPANTS_SHOW_SUCCESS`;
export const PARTICIPANTS_SHOW_FAILURE = `${PREFIX}/PARTICIPANTS_SHOW_FAILURE`;
/** CRUD */
export const GET_REQUEST = `${PREFIX}/GET_REQUEST`;
export const POST_REQUEST = `${PREFIX}/POST_REQUEST`;
export const PUT_REQUEST = `${PREFIX}/PUT_REQUEST`;
export const DELETE_REQUEST = `${PREFIX}/DELETE_REQUEST`;
/** Auth */
export const RUN = `${PREFIX}/RUN`;
export const REFRESH_TOKENS = `${PREFIX}/REFRESH_TOKENS`;
export const LOGIN = `${PREFIX}/LOGIN`;
export const LOGOUT = `${PREFIX}/LOGOUT`;
