/** Constants */
const PREFIX = '@@AWX';
/** UI */
export const UI = `${PREFIX}_UI`;
export const ERROR = `${PREFIX}_ERROR`;
export const LOADING = `${PREFIX}_LOADING`;
export const NOOP = `${PREFIX}_NOOP`;
/** Labs */
export const LABS_INDEX_REQUEST = `${PREFIX}/LABS_INDEX_REQUEST`;
export const LABS_INDEX_SUCCESS = `${PREFIX}/LABS_INDEX_SUCCESS`;
export const LABS_INDEX_FAILURE = `${PREFIX}/LABS_INDEX_FAILURE`;
export const LABS_CREATE_REQUEST = `${PREFIX}/LABS_CREATE_REQUEST`;
export const LABS_CREATE_SUCCESS = `${PREFIX}/LABS_CREATE_SUCCESS`;
export const LABS_CREATE_FAILURE = `${PREFIX}/LABS_CREATE_FAILURE`;
export const LABS_DELETE_REQUEST = `${PREFIX}/LABS_DELETE_REQUEST`;
export const LABS_DELETE_SUCCESS = `${PREFIX}/LABS_DELETE_SUCCESS`;
export const LABS_DELETE_FAILURE = `${PREFIX}/LABS_DELETE_FAILURE`;
export const LABS_UPDATE_REQUEST = `${PREFIX}/LABS_UPDATE_REQUEST`;
export const LABS_UPDATE_SUCCESS = `${PREFIX}/LABS_UPDATE_SUCCESS`;
export const LABS_UPDATE_FAILURE = `${PREFIX}/LABS_UPDATE_FAILURE`;
export const LABS_SHOW_REQUEST = `${PREFIX}/LABS_SHOW_REQUEST`;
export const LABS_SHOW_SUCCESS = `${PREFIX}/LABS_SHOW_SUCCESS`;
export const LABS_SHOW_FAILURE = `${PREFIX}/LABS_SHOW_FAILURE`;
/** CRUD */
export const GET_REQUEST = `${PREFIX}/GET_REQUEST`;
export const POST_REQUEST = `${PREFIX}/POST_REQUEST`;
export const PUT_REQUEST = `${PREFIX}/PUT_REQUEST`;
export const DELETE_REQUEST = `${PREFIX}/DELETE_REQUEST`;
/** Auth */
export const RUN = `${PREFIX}/RUN`;
export const REFRESH_TOKENS = `${PREFIX}/REFRESH_TOKENS`;
export const LOGIN = `${PREFIX}/LOGIN`;
export const LOGOUT = `${PREFIX}/LOGOUT`;
